name: Compile and test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: make
    - name: install dependencies
      run: sudo apt-get update -y && sudo apt-get install --yes cmocka
    - name: tests
      run: cd tests && make && ./test.out
